# Radio Commands
_RADIO_GET_STATUS = 0xC0
_RADIO_WRITE_REGISTER = 0x18
_RADIO_READ_REGISTER = 0x19
_RADIO_WRITE_BUFFER = 0x1A
_RADIO_READ_BUFFER = 0x1B
_RADIO_SET_SLEEP = 0x84
_RADIO_SET_STANDBY = 0x80
_RADIO_SET_TX = 0x83
_RADIO_SET_RX = 0x82
_RADIO_SET_CAD = 0xC5
_RADIO_SET_PACKETTYPE = 0x8A
_RADIO_GET_PACKETTYPE = 0x03
_RADIO_SET_RFFREQUENCY = 0x86
_RADIO_SET_TXPARAMS = 0x8E
_RADIO_SET_CADPARAMS = 0x88
_RADIO_SET_BUFFERBASEADDRESS = 0x8F
_RADIO_SET_MODULATIONPARAMS = 0x8B
_RADIO_SET_PACKETPARAMS = 0x8C
_RADIO_GET_RXBUFFERSTATUS = 0x17
_RADIO_GET_PACKETSTATUS = 0x1D
_RADIO_GET_RSSIINST = 0x1F
_RADIO_SET_DIOIRQPARAMS = 0x8D
_RADIO_GET_IRQSTATUS = 0x15
_RADIO_CLR_IRQSTATUS = 0x97
_RADIO_SET_REGULATORMODE = 0x96
_RADIO_SET_AUTOFS = 0x9E
_RADIO_SET_RANGING_ROLE = 0xA3
_PACKET_TYPE_LORA = 0x01
_PACKET_TYPE_RANGING = 0x02
_PACKET_HEADER_EXPLICIT = 0x00  # varriable length, header included
_PACKET_HEADER_IMPLICIT = 0x80  # fixed length, no header in packet
_PACKET_CRC_MODE_ON = 0x20  # 32
_PACKET_CRC_MODE_OFF = 0x00
_PACKET_IQ_INVERT = 0x00
_PACKET_IQ_NORMAL = 0x40  # 64
_XTAL_FREQ = 52000000
_FREQ_STEP = _XTAL_FREQ / 262144

# Radio Head Constants
_RH_BROADCAST_ADDRESS = 0xFF
_RH_FLAGS_ACK = 0x80
_RH_FLAGS_RETRY = 0x40

_irq1Def = (
    "RngSlaveReqDiscard",
    "RngMasterResultValid",
    "RngMasterTimeout",
    "RngMasterReqValid",
    "CadDone",
    "CadDetected",
    "RxTxTimeout",
    "AdvRngDone",
)
_irq2Def = (
    "TxDone",
    "RxDone",
    "SyncWrdValid",
    "SyncWrdErr",
    "HeaderValid",
    "HeaderErr",
    "CrcErr",
    "RngSlaveResponseDone",
)
